//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acraserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_Loan_Types
    {
        public int acra_l_type_ID { get; set; }
        public string acra_l_type { get; set; }
    }
}
