//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acraserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_TotalOfLnAndGr
    {
        public long cLoansId { get; set; }
        public Nullable<long> resultId { get; set; }
        public Nullable<int> lType { get; set; }
        public Nullable<int> vCurrent { get; set; }
        public Nullable<int> vClosed { get; set; }
        public Nullable<int> vTotal { get; set; }
    }
}
