//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acraserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRAUser
    {
        public int u_acra_ID { get; set; }
        public Nullable<int> fk_user_ID { get; set; }
        public string acra_user { get; set; }
        public byte[] acra_pwd { get; set; }
    }
}
