//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acraserv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_ReqStatus
    {
        public long req_ID { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public Nullable<int> req_type { get; set; }
        public string req_result { get; set; }
    }
}
